### ISSUE TITLE
jvm options for java 11

### ISSUE THREAD

**Issue by markri** [voxpupuli/puppet-logstash#397]
Currently the module doesn't work out of the box with Java 11 this is because there are 2 JVM properties which are incompatible with Java 11 (they are written with the jvm.options.erb template). There needs to be some way to either:

- support different templates for different java versions
- make jvm options more configurable by removing the 'defaults{}' **hash** from jvm.options.erb and put it in a hash in service.pp (service.pp already contains a **list** $default_jvm_options, but this variable doesnt seem to be used)

As a temporary workaround to keep me going I'm now using this ugly fix:
(the -D doesn't do anything but prevents the template writing incompatible JVM options)

```
    jvm_options => [
      '-DUseParNewGC=disable', 
      '-DUseConcmarksweepgc=disable',
      '-XX:+UseG1GC',
    ]
```

**Comment by molivier-fcms** [comment]
I agree with you, these GC options prevent logstash to work.
Thank you for your workaround, I was reluctant to modify the template.

**Comment by avitacco** [comment]
@markri Thank you for this, you saved me (probably) hours of work.

**Comment by pedro-te** [comment]
@markri thank you for this as well, this helped me too.

**Comment by xorpaul** [comment]
After the merge of #412 to use this workaround you need to use:

```yaml
logstash::jvm_options:
  - '-DUseParNewGC=disable'
  - '-DUseConcMarkSweepGC=disable'
  - '-XX:+UseG1GC'
```
or
```puppet
   jvm_options => [
      '-DUseParNewGC=disable', 
      '-DUseConcMarkSweepGC=disable',
      '-XX:+UseG1GC',
    ]
```
