### ISSUE TITLE
Does this module support Amazon Linux 2023

### ISSUE THREAD

**Issue by thangavelua1** [voxpupuli/puppet-logstash#447]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

**Comment by TheMeier** [comment]
You can find the list of supported OSes in https://github.com/voxpupuli/puppet-logstash/blob/master/metadata.json

Since AmazonLinux is in part based on Fedora  34, 35, 36, and CentOS 9 Stream, it might work.
